title: Yosati prezinta
author: Yosati
email: yosati18@gmail.com
description: Aceasta este derscrierea siteului meu !!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima 
